### ISSUE TITLE
Get an error , how to solve it?

### ISSUE THREAD

**Issue by dengzq** [aryarohit07/FrescoFaceDetectionProcessor#1]
I used this lib step by step and get an error below : 
Error creating remote native handle.  
com.google.android.gms.internal.zzsu$zza: No acceptable module found. Local version is 0 and remote version is 0.

How to solve it ? i'm fresh in android. Thanks！
If you can add a demo in the zip, it wound be better!

**Comment by aryarohit07** [comment]
Hi @dzqleo , I think your device doesn't have a current version of Google Play services. You can see the version by going to Settings > Apps > All > Google Play services. The version should be 7.8.95 or greater.
